name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Configure AWS credentials fron account
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
          FROM_PATH: "."
          DEST_PATH: "s3://${{ secrets.BUCKET_NAME }}"
      - name: Copy Files to s3
        run: |
          aws s3 cp . s3://${{ secrets.BUCKET_NAME }} --recursive
